
services:
  client:
    # image: datsindia/itms-frontend:release-v1.0.52
    container_name: client-river
    restart: always
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
      - 80
  server:
    # image: datsindia/itms-frontend:release-v1.0.52
    container_name: server-monutain
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    expose:
      - 4000
      - 80
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - ENVIRONMENT=development
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local